# Generated by Django 5.1.2 on 2024-10-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='salario',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dtNasc',
            field=models.DateField(help_text='Data de nascimento do usuário', verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(help_text='E-Mail do usuário', max_length=254),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(help_text='Idade do usuário'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(help_text='Nome do usuário', max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(help_text='Telefone do usuário', max_length=20),
        ),
    ]
